### ISSUE TITLE
[10.0] Websitelivechat: Live chat not displayed

### ISSUE THREAD

**Issue by hugho-ad** [Vauxoo/runbot#15]
Live chat is not displayed because the im_status is not updated
https://github.com/Vauxoo/odoo/blob/10.0/addons/bus/models/res_users.py#L12-L29
![image](https://user-images.githubusercontent.com/10233975/29134414-223343fa-7cfc-11e7-9b65-664c6e3f647d.png)

Talking wit @moylop260 , this bug is related with the requirements installed in docker containers

**Comment by hugho-ad** [comment]
FYI @moylop260, the issue persists

Regards!

**Comment by moylop260** [comment]
I think is a missing configuration for nginx:
 - https://www.odoo.com/es_ES/forum/ayuda-1/question/im-chat-not-work-with-database-which-installed-in-another-server-96895
 - https://www.odoo.com/es_ES/forum/ayuda-1/question/discus-not-realtime-error-110975

Because using the port directly works!

I mean,
`subdomain.host` don't work
`host:port` works

@ruiztulio this issue is reproduced from testing instances too.
Could you (something your team) to fix it for production, testing and runbot, please?

@hugho-ad 
Could you upload image where testing is working using port but failing using subdomain?

**Comment by ruiztulio** [comment]
@moylop260 we install this configuration by default in the servers (look [here](https://github.com/Vauxoo/ansible-deployment/blob/master/roles/provision_base/templates/https-site.jinja#L31)) but the runbot is different because we have a global rule to redirect all traffic to the runbot nginx:

![a](http://screenshots.vauxoo.com/tulio/18444822117-IsloXUyNqY.jpg)

Then that nginx is supposed to [redirect the LP traffic to the appropiate port](https://github.com/Vauxoo/odoo-extra/blob/9.0/runbot/runbot.xml#L702), so as far as I can see the configuration seems to be done, but we are still missing something.

@hugho-ad can you tell me which test instance is not working properly?

**Comment by hugho-ad** [comment]
@ruiztulio 
for example in https://v10.abastotal.com and http://test.imeqmo.com/
and runbot build like http://39472-10-0-cb4dff.runbot.vauxoo.com/shop or http://39422-10-0-0419ee.runbot.vauxoo.com/shop

**Comment by hugho-ad** [comment]
@moylop260 you rigth, when I acces to the build by the url `host:port`, live chat is displayed
![image](https://user-images.githubusercontent.com/10233975/29149372-46eae198-7d39-11e7-80a0-fe87798b1bac.png)

**Comment by ruiztulio** [comment]
@hugho-ad test.imeqmo.com had 0 workers:

![a](http://screenshots.vauxoo.com/tulio/19241422117-qSKtbbonYm.jpg)

Changed to 3:
![b](http://screenshots.vauxoo.com/tulio/19310722117-RSENEeLsjB.jpg)

Restart the instance and the chat is working:

![c](http://screenshots.vauxoo.com/tulio/19300222117-czZNZJHuCV.jpg)

![d](http://screenshots.vauxoo.com/tulio/19280922117-VWIJP7hS52.jpg)

Abastotal 10.0:
![a](http://screenshots.vauxoo.com/tulio/19314622117-MM2aGAjrv4.jpg)

I didn't change it because I have to restart the instance, but it should work after that.

Most of the issue we had with the chat are because of this. I have to check the runbot ones

**Comment by hugho-ad** [comment]
Very Thanks @ruiztulio 

Regards!

**Comment by moylop260** [comment]
I re-open this issue because is not fixed for runbot yet.
I saw that odoo redirect the longpolling-port [here](https://github.com/odoo/odoo-extra/blob/e412bc2987a54d6ea60af49aba1b032dea02f9b5/runbot/runbot.py#L1061-L1064) and we need use this feature from [MQT](https://github.com/Vauxoo/maintainer-quality-tools/blob/ab6ec8817931e23f6b3b12ffc36a21ea3990b962/travis/test_server.py#L550)


@JesusZapata Could you help us to fix it?

**Comment by moylop260** [comment]
Or wait... we can use the extra port because we are using it for ssh connection feature.
It can't fix it for runbot
